# -*- coding: utf-8 -*-
"""Digital_Twin_Student_B.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QbW1IuQLl6PC8-kRG27m8MUNWepA-q6D
"""

pip install scipy numpy matplotlib pandas

# Solar Panel Model (The I-V and P-V Curves)

import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import fsolve

# ── Panel Parameters (typical 50W panel) ──────────────────────────
Isc_ref  = 3.0      # Short-circuit current at STC [A]
Voc_ref  = 21.6     # Open-circuit voltage at STC [V]
Imp      = 2.8      # Current at max power [A]
Vmp      = 17.8     # Voltage at max power [V]
n        = 1.3      # Ideality factor
Rs       = 0.5      # Series resistance [Ω]
Rsh      = 300.0    # Shunt resistance [Ω]
T_ref    = 298.15   # Reference temperature [K] = 25°C
q        = 1.602e-19
k        = 1.381e-23

def Vt(T):
    return n * k * T / q   # Thermal voltage

def Iph(G, T, G_ref=1000):
    return Isc_ref * (G / G_ref) * (1 + 0.0045*(T - T_ref))

def I0(T):
    return Isc_ref / (np.exp(Voc_ref / Vt(T)) - 1)

def pv_current(V, G=1000, T=298.15):
    """Solve for I given V using the single diode model."""
    def equation(I):
        return (I - Iph(G, T)
                + I0(T)*(np.exp((V + I*Rs)/Vt(T)) - 1)
                + (V + I*Rs)/Rsh)
    I_guess = Iph(G, T) * 0.9
    I_sol, _, flag, _ = fsolve(equation, I_guess, full_output=True)
    return max(I_sol[0], 0)

# ── Generate I-V and P-V curves for different irradiance levels ────
V_range = np.linspace(0, Voc_ref, 200)
irradiance_levels = [1000, 700, 400, 200]  # W/m²
colors = ['#f59e0b', '#f97316', '#6366f1', '#64748b']

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('Solar Panel Model — Single Diode Model\n(Student B: Digital Twin)',
             fontsize=13, fontweight='bold')

for G, color in zip(irradiance_levels, colors):
    I_vals = np.array([pv_current(v, G=G) for v in V_range])
    P_vals = V_range * I_vals
    label = f'G = {G} W/m²'
    ax1.plot(V_range, I_vals, color=color, lw=2, label=label)
    ax2.plot(V_range, P_vals, color=color, lw=2, label=label)
    # Mark MPP
    mpp_idx = np.argmax(P_vals)
    ax2.plot(V_range[mpp_idx], P_vals[mpp_idx], 'k^', ms=7)

ax1.set(xlabel='Voltage (V)', ylabel='Current (A)', title='I-V Characteristic Curves')
ax1.legend(); ax1.grid(True, alpha=0.3)
ax2.set(xlabel='Voltage (V)', ylabel='Power (W)', title='P-V Curves — ▲ = Maximum Power Point')
ax2.legend(); ax2.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('pv_model.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ PV Model plotted successfully")

#Since my teammates haven't connected the ESP32 yet (or I just want to test independently), I will generate realistic synthetic sensor data.
#This is standard engineering practice — it's called a test bench.

import pandas as pd

np.random.seed(42)
time_seconds = np.arange(0, 3600)  # 1 hour simulation

# Simulate solar irradiance: starts clear, cloud passes at t=1200s, recovers
def irradiance_profile(t):
    base = 900
    cloud1 = -600 * np.exp(-((t - 1200)**2) / (2*150**2))  # cloud at 20 min
    cloud2 = -400 * np.exp(-((t - 2500)**2) / (2*200**2))  # cloud at 41 min
    noise  = np.random.normal(0, 20, len(t))
    return np.clip(base + cloud1 + cloud2 + noise, 50, 1000)

G_profile = irradiance_profile(time_seconds)

# Calculate panel output at each second
V_op = 17.0  # Operating voltage (assume MPPT)
I_panel = np.array([pv_current(V_op, G=g) for g in G_profile])
P_solar  = V_op * I_panel

# Battery and load
P_load    = 25.0          # Constant 25W load
C_bat_Ah  = 10.0          # 10 Ah battery
V_bat     = 12.0          # 12V nominal
C_bat_Wh  = C_bat_Ah * V_bat  # 120 Wh

SOC = np.zeros(len(time_seconds))
SOC[0] = 90.0  # Start at 90%
I_battery = np.zeros(len(time_seconds))

for t in range(1, len(time_seconds)):
    P_net = P_solar[t] - P_load           # Positive = charging
    I_battery[t] = P_net / V_bat          # + = charging, - = discharging
    delta_SOC = (I_battery[t] / C_bat_Ah) * (1/3600) * 100  # per second
    SOC[t] = np.clip(SOC[t-1] + delta_SOC, 0, 100)

# Add measurement noise (simulating real sensor imperfection)
V_measured = V_bat + np.random.normal(0, 0.05, len(time_seconds))
I_measured = I_battery + np.random.normal(0, 0.02, len(time_seconds))

# Package as DataFrame (mimics what ESP32 would send via MQTT)
df = pd.DataFrame({
    'time_s':      time_seconds,
    'G_Wm2':       G_profile,
    'V_measured':  V_measured,
    'I_measured':  I_measured,
    'SOC_true':    SOC,
    'P_solar':     P_solar,
    'P_load':      P_load
})

df.to_csv('sensor_data.csv', index=False)
print(f"✅ Generated {len(df)} seconds of sensor data")
print(df.head(10))

#This is the heart of the work. The twin receives data and stays synchronized

def digital_twin_sync(df, C_bat_Ah=10.0, V_bat=12.0, sync_window=60):
    """
    Digital Twin with state synchronization.
    Every `sync_window` seconds, the model re-anchors to real sensor data.
    """
    n = len(df)
    SOC_twin   = np.zeros(n)
    SOC_twin[0] = df['SOC_true'].iloc[0]  # Initialize from real data
    sync_error  = np.zeros(n)
    prediction_horizon = np.zeros(n)  # Minutes until SOC hits 20%

    for t in range(1, n):
        row = df.iloc[t]

        # ── Twin's own physics calculation ─────────────────────────
        P_net   = row['P_solar'] - row['P_load']
        I_bat   = P_net / V_bat
        delta   = (I_bat / C_bat_Ah) * (1/3600) * 100
        SOC_twin[t] = np.clip(SOC_twin[t-1] + delta, 0, 100)

        # ── State Synchronization (every sync_window seconds) ──────
        # In real system: this uses V_measured + I_measured from ESP32
        # Here we use SOC_true as the "physical system" reference
        if t % sync_window == 0:
            # Re-anchor model to physical reality
            SOC_twin[t] = row['SOC_true'] * 0.98   # 98% trust in sensor

        # ── Synchronization Error ──────────────────────────────────
        if row['SOC_true'] > 0:
            sync_error[t] = abs(SOC_twin[t] - row['SOC_true']) / row['SOC_true'] * 100

        # ── Prediction: minutes until SOC = 20% ───────────────────
        discharge_rate = -delta * 60  # % per minute (if negative = discharging)
        if discharge_rate > 0 and SOC_twin[t] > 20:
            prediction_horizon[t] = (SOC_twin[t] - 20) / discharge_rate
        else:
            prediction_horizon[t] = 999  # Charging, no concern

    return SOC_twin, sync_error, prediction_horizon

SOC_twin, sync_error, pred_horizon = digital_twin_sync(df)
print(f"✅ Twin simulation complete")
print(f"   Max sync error: {sync_error.max():.2f}%")
print(f"   Mean sync error: {sync_error.mean():.2f}%")
print(f"   SUCCESS: Error < 5%? {'✅ YES' if sync_error.max() < 5 else '❌ NO'}")

t_min = df['time_s'] / 60  # Convert to minutes

fig, axes = plt.subplots(3, 1, figsize=(14, 12))
fig.suptitle('Digital Twin — State Synchronization Results\n(Student B Deliverable)',
             fontsize=14, fontweight='bold')

# ── Plot 1: Physical vs Virtual SOC ───────────────────────────────
ax = axes[0]
ax.plot(t_min, df['SOC_true'], 'b-',  lw=2,   label='Physical System (Real SOC)', alpha=0.9)
ax.plot(t_min, SOC_twin,       'r--', lw=1.5, label='Digital Twin (Virtual SOC)', alpha=0.9)
ax.axhline(20, color='red', ls=':', lw=1.5, label='Critical Threshold (20%)')
ax.fill_between(t_min, df['SOC_true'], SOC_twin, alpha=0.15, color='orange', label='Sync Error Region')
ax.set(ylabel='SOC (%)', title='Physical vs Virtual — SOC Convergence')
ax.legend(loc='upper right'); ax.grid(True, alpha=0.3)
ax.set_ylim(0, 100)

# ── Plot 2: Synchronization Error ─────────────────────────────────
ax = axes[1]
ax.fill_between(t_min, sync_error, alpha=0.4, color='#f97316')
ax.plot(t_min, sync_error, color='#ea580c', lw=1.5, label='Sync Error (%)')
ax.axhline(5, color='red', ls='--', lw=2, label='5% Limit (Success Criterion)')
ax.set(ylabel='Error (%)', title='Synchronization Error — Must Stay Below 5%')
ax.legend(); ax.grid(True, alpha=0.3)

# ── Plot 3: Solar Irradiance (context) ────────────────────────────
ax = axes[2]
ax.fill_between(t_min, df['G_Wm2'], alpha=0.4, color='#f59e0b')
ax.plot(t_min, df['G_Wm2'], color='#d97706', lw=1.5)
ax.set(xlabel='Time (minutes)', ylabel='Irradiance (W/m²)',
       title='Solar Irradiance Profile — Cloud Events Visible')
ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('sync_results.png', dpi=150, bbox_inches='tight')
plt.show()

#Prediction Plot (Showing the "Predictive" Value)

fig, ax = plt.subplots(figsize=(14, 5))

# Only show prediction when it's meaningful (< 60 min)
pred_display = np.where(pred_horizon < 60, pred_horizon, np.nan)

ax.plot(t_min, df['SOC_true'], 'b-', lw=2, label='Battery SOC (%)', alpha=0.8)
ax2 = ax.twinx()
ax2.plot(t_min, pred_display, 'g-', lw=1.5, alpha=0.7, label='Predicted Time to Critical (min)')
ax2.set_ylabel('Minutes Until SOC = 20%', color='green')

ax.axhline(20, color='red', ls=':', lw=2, label='Critical SOC = 20%')
ax.set(xlabel='Time (minutes)', ylabel='SOC (%)',
       title='Digital Twin Prediction Engine — Time to Critical Battery Level')
ax.legend(loc='upper left'); ax2.legend(loc='upper right')
ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('prediction.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ All plots generated and saved")

# Add prediction to dataframe for Student D
df['minutes_to_critical'] = pred_horizon
df['alert'] = pred_horizon < 15  # True = Student D should shed load
df.to_csv('twin_output_for_studentD.csv', index=False)